Core hole vasp
nomad-coe/electronic-parsers pull request #181
Opened 2023-11-15 13:43 UTC by ndaelman-hu

Identification of the core-hole (location + orbital level) with appropriate references to `run.system.atoms_group` so topology view is leveraged. This will be further extended to FHIaims and ATOMPAW in separate PRs.

2023-11-15 13:44 UTC, ndaelman-hu commented
Left to do:
- [ ] Apply ICORELEVEL tag at the electron count level

2023-11-16 14:58 UTC, JosePizarro3 requested changes

2023-11-16 14:58 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +            atoms_group=sub_groups,
Yes, this is the wrong point I am mentioning in the Gitlab. I will do a more thorough review, but initially I'd say that `atoms_group` is an unecesserary repetition, as you are creating this extra layer.

You only need to store something like:
```
atoms_group = AtomsGroup(
   type='core_hole',
   label=elem_label,
   n_atoms=len(atom_ids),
   atom_indices=atom_ids,
)
```

Anything else (`label='core-hole_' + elem_label` and `atoms_group=sub_groups`) is the repetition I am mentioning that you don't need 🙂

2023-11-17 18:17 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +            atoms_group=sub_groups,
> initially I'd say that atoms_group is an unecesserary repetition

Point taken. Let's keep this discussion over at Gitlab, and if we decide against this layer, I'll simply remove it.

2023-11-17 19:20 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +            atoms_group=sub_groups,
> Anything else (label='core-hole_' + elem_label and atoms_group=sub_groups) is the repetition I am mentioning that you don't need

Yeah, the current `label` was just a placeholder, so feel free to raise suggestions.
I applied the code you posted, but this means that the term _core-hole_ isn't visible at the 2nd visual layer anymore (fig. 1).
If we go this way, we really do need a 3rd visual layer, just to denote the type. Else, this information should be in the title.

Something similar happens with Projection, where the word doesn't show up at all... In the example, it's just CU (fig. 2).
Btw, the **all-caps is a nightmare for elemental labels**... I'd like to amend that together with Lauri.

![Screenshot from 2023-11-17 20-15-39](https://github.com/nomad-coe/electronic-parsers/assets/107392603/c2e2dd6c-a403-4c83-9302-b6123ac95345)

![Screenshot from 2023-11-17 20-17-41](https://github.com/nomad-coe/electronic-parsers/assets/107392603/99ed6a67-56c9-44a4-b0aa-2dac2873563a)

2023-11-20 09:37 UTC, JosePizarro3 reviewed
Very nice. Please, don't forget to change also `workflowparsers/quantum_espresso_xspectra` with the new `CoreHoleSpectra`.

I will keep up with the discussion about nesting AtomsGroup.

2023-11-20 09:37 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +        sec_method.x_vasp_atom_kind_refs = sec_method.atom_parameters  # TODO: deprecate x_vasp_atom_kind_refs?
Yes, please. Deprecate it.

2023-11-20 09:37 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +    def parse_configurations(self, atoms_group: Union[AtomsGroup, None] = None):
Is this the correct typing? Shouldn't be `atoms_group: AtomsGroup = None`?

2023-11-20 09:37 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +        self.parse_configurations(
It seems to me that `self.parse_configurations` will be more readable if using `method_dict` as an input, and then within the function you resolve `atoms_group`.

Just a small style detail.

2023-11-20 09:43 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +            atoms_group=sub_groups,
My main concern here is that: 3 layers is unnecessary, as we only need (1) the original crystal + (2) the specific `active_atoms` used and their environments. 

Now I see that the naming for `label` might be confusing. We can then go back to your case (`label=f'core_hole_{elem_id}'`) or define in gitlab a new structural type called `'active_atoms'` (or `['core_hole_atoms', 'projection_atoms']`. I'd personally prefer the first option, but maybe the second has its benefits

2023-11-20 10:18 UTC, ondracka commented
I can't comment much on the VASP parser changes, but rather on the general metainfo changes (doing this here due to no access to the upstream github). In general this would suit my needs, but at least for Wien2k for states with n>1 where a spin-orbit splitting happens, like 2p states, I can actually specify if I want the corehole for 2p1/2 or 2p3/2, and equivalently for d and f states. I could likely also specify up and down spin state with Wien2k (but I never did that).
I checked the VASP docs and there is seems this is not possible, but I would expect that maybe other all-electron codes can do this as well.
My another favorite code OpenMX also allows all kinds of core-holes (there is nice table at https://www.openmx-square.org/openmx_man3.9/node192.html) there it also depends whether one has collinear or non-collinear spin polarization. So maybe we need more quantum numbers...

2023-11-20 10:32 UTC, ondracka commented
One question is if we also want to somehow explicitly include somewhere the charge info at this point. Together with with the corehole usually also comes the question about where to put the extra charge. I.e., if the electron was removed from the cell (and a homogeneous background change was added so that the calculations behave in a sane way) but it is actually a charged cell (this is usually done for insulators) or if the electron was placed at the Fermi level (this would make sense for core-hole in metals). This is not related just to the core-hole and is relevant also for other methods (for charged-defect calculations in insulators, etc.). I believe VASP always adds the background charge automatically for example (and it will probably diverge for a true charged cell anyway).)

2023-11-20 11:12 UTC, ndaelman-hu commented
> I can't comment much on the VASP parser changes, but rather on the general metainfo changes (doing this here due to no access to the upstream github). In general this would suit my needs, but at least for Wien2k for states with n>1 where a spin-orbit splitting happens, like 2p states, I can actually specify if I want the corehole for 2p1/2 or 2p3/2, and equivalently for d and f states. I could likely also specify up and down spin state with Wien2k (but I never did that). I checked the VASP docs and there is seems this is not possible, but I would expect that maybe other all-electron codes can do this as well. My another favorite code OpenMX also allows all kinds of core-holes (there is nice table at https://www.openmx-square.org/openmx_man3.9/node192.html) there it also depends whether one has collinear or non-collinear spin polarization. So maybe we need more quantum numbers...

Thank you for pointing that out! I'll open up tickets for OpenMX then, and merge the schema after having working parsers for both parsers.

2023-11-20 11:43 UTC, ndaelman-hu commented
> One question is if we also want to somehow explicitly include somewhere the charge info at this point. Together with with the corehole usually also comes the question about where to put the extra charge. I.e., if the electron was removed from the cell (and a homogeneous background change was added so that the calculations behave in a sane way) but it is actually a charged cell (this is usually done for insulators) or if the electron was placed at the Fermi level (this would make sense for core-hole in metals). This is not related just to the core-hole and is relevant also for other methods (for charged-defect calculations in insulators, etc.). I believe VASP always adds the background charge automatically for example (and it will probably diverge for a true charged cell anyway).)

Very good point! We keep track of the no. (valence) electrons and overall system charge under `run.method.electronic`. We could just improve the normalizers here and make this information more visible in the Entry Overview. This would allow for finding core-holes with the electron exited to the Fermi level or the vacuum.

But maybe we want something **more explicit** when core-holes are being used? VASP also allows partial core-holes, as well as initial and final state approximations. @ondracka Are these also used in Wien2k or OpenMX? That would help me decide on their placement in the schema.

2023-11-20 11:51 UTC, ondracka commented
> Thank you for pointing that out! I'll open up tickets for OpenMX then, and merge the schema after having working parsers for both parsers.

Let me know if you need some test-cases. Here is a simple C 1s corehole in OpenMX: https://nomad-lab.eu/prod/v1/staging/gui/search/calculations/entry/id/zLqikxv-mfCrI3sC9EuXmqfEX04T but I can also produce something simpler and more suitable for eventual inclusion in parser unit tests (or also for the other core-holes than 1s). For Wien2k I have some N1s core-hole: https://nomad-lab.eu/prod/v1/staging/gui/search/entries/entry/id/Fbk7yucgh7CxMsp0RKdR263J_OIj , O1s https://nomad-lab.eu/prod/v1/staging/gui/search/entries/entry/id/1GH5Rvm-t2tAYPrL9UdtkShaas3s, or Ti2p3/2 https://nomad-lab.eu/prod/v1/staging/gui/search/entries/entry/id/s5W753xr30EulmEUzsu75HMtxZMh coreholes in NOMAD already.

2023-11-20 11:57 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +    def parse_configurations(self, atoms_group: Union[AtomsGroup, None] = None):
It can be simplified, yes, but not to your suggestion. The type `AtomsGroup` only includes the class, not `None` objects.

I will change it to `def parse_configurations(self, atoms_group: Optional[None] = None):`

2023-11-20 11:58 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +        self.parse_configurations(
Sounds fine. I'll just add an explanation on the exact meaning and use of `method_dict`.

2023-11-20 12:05 UTC, ondracka commented
> Very good point! We keep track of the no. (valence) electrons and overall system charge under `run.method.electronic`. We could just improve the normalizers here and make this information more visible in the Entry Overview. This would allow for finding core-holes with the electron exited to the Fermi level or the vacuum.
> 
> But maybe we want something **more explicit** when core-holes are being used? VASP also allows partial core-holes, as well as initial and final state approximations. @ondracka Are these also used in Wien2k or OpenMX? That would help me decide on their placement in the schema.

Partial core-holes with arbitrary fraction are easy in Wien2k (and probably other LAPW all electron codes), however I'm not aware that this would be possible in OpenMX.
Regarding the "initial" states, i.e., I assume you are referring to what VASP would be doing with ICORELEVEL=1 this is what all-electron codes do by default (and at that point there is no core-hole at all actually, just VASP includes the core-level in the calculations instead of using pseudopotential), so for all-electron codes this is just standard groundstate. For OpenMX one actually needs specific pseudopotential and basis set for the atom with the core-hole that include the core-level in question, but no other setting are needed. So I think that for VASP run with ICORELEVEL=1 there would be no CoreHole section and the fact that the extra electron are included would be encoded somehow in the pseudopotential section.
"Final state" is the true core-hole calculation.

2023-11-20 12:55 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +    def parse_configurations(self, atoms_group: Union[AtomsGroup, None] = None):
That's a weird typing (Optional None to None?), but nvm, this is then deprecated if you pass `method_dict: dict = {}` 😄

2023-11-23 06:58 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +    def parse_configurations(self, atoms_group: Union[AtomsGroup, None] = None):
Oops, that's a typo. It has to be `def parse_configurations(self, atoms_group: Optional[AtomsGroup] = None)`, obviously.

2023-12-01 10:21 UTC, ndaelman-hu commented
> but at least for Wien2k for states with n>1 where a spin-orbit splitting happens, like 2p states, I can actually specify if I want the corehole for 2p1/2 or 2p3/2, and equivalently for d and f states. I could likely also specify up and down spin state with Wien2k (but I never did that).

This supported now.

> My another favorite code OpenMX also allows all kinds of core-holes (there is nice table at https://www.openmx-square.org/openmx_man3.9/node192.html) there it also depends whether one has collinear or non-collinear spin polarization. So maybe we need more quantum numbers...

Let me look into this. Maybe support for non-collinear calculations requires its own PR. Feel free to make any suggestions.

2023-12-01 10:27 UTC, ndaelman-hu commented
> Let me know if you need some test-cases. Here is a simple C 1s corehole in OpenMX: https://nomad-lab.eu/prod/v1/staging/gui/search/calculations/entry/id/zLqikxv-mfCrI3sC9EuXmqfEX04T but I can also produce something simpler and more suitable for eventual inclusion in parser unit tests (or also for the other core-holes than 1s).

@ondracka It seems that OpenMX reads the pseudopotentials from a different folder. Since the files are not copied over to the calculation folder, I guess it's unlikely that people will upload them.

Personally, I prefer reading the original pseudopotential file, but I guess that here it's better to build out an interpreter of the filename. Do you agree? How reliable is this approach?

2023-12-01 10:53 UTC, ndaelman-hu commented
> Regarding the "initial" states, i.e., I assume you are referring to what VASP would be doing with ICORELEVEL=1

Indeed, this is the terminology they use in the [VASP Wiki](https://www.vasp.at/wiki/index.php/ICORELEVEL).

> this is what all-electron codes do by default (and at that point there is no core-hole at all actually, just VASP includes the core-levels in the calculations instead of using pseudopotential), so for all-electron codes this is just standard groundstate.

@ondracka I fully agree with your explanation of the methodology.
However, in most contexts, ICORELEVEL=1is employed with Koopmans theorem or Slater's Transition method to produce CLBEs. One such example (not with VASP) would be [here](https://pubs.aip.org/aip/jcp/article/158/9/094111/2881303/Slater-transition-methods-for-core-level-electron). An overview of the various approaches is given in the first 2 paragraphs on page 2.

So, I see 2 options:
1. I infer that anyone using I**CORELEVEL**=1, does so with the intention of computing a core-level. There are several ways to approximate this (Koopman, or any of the fractional occupations listed above). If I know which state is targeted, I could even produce all the numbers.
2. I leave it up to the user to specify if they used the orbitals for computing the core-hole, as well as the actual scheme they used. This would come closer to what you proposed.

Let me know what you think.

2023-12-01 11:03 UTC, ondracka commented
> Let me look into this. Maybe support for non-collinear calculations requires its own PR. Feel free to make any suggestions.

I think this is OK for now, lets revisit the non-collinear case when we actually have some use cases...

2023-12-01 11:06 UTC, ondracka commented
> Personally, I prefer reading the original pseudopotential file, but I guess that here it's better to build out an interpreter of the filename. Do you agree? How reliable is this approach?

I'm only aware of the one set of pseudos provided by the OpenMX developers (versioned by the releases), so it should be quite reliable (unless people really handcraft their own pseudos, but that should be not too common).

2023-12-04 06:57 UTC, ondracka commented
I went quickly through the actual code changes and while I was not reviewing the logic per se, the general idea how things are done now looks fine, so I'm happy with how this turned out in general.

2023-12-11 17:36 UTC, ndaelman-hu commented
@ladinesa @lauri-codes Design question: core-holes are kind of connected to various other sections (too much interconnectivity):
1. Each `CoreHole` has to reference an `AtomsGroup` (this also applies to other sections, such as `CoreHoleSpectra`). Atm, I set these manually in the parsers, but I get the feeling that this could be done by a normalizer. I guess one could loop over all `AtomParameters` which contain `CoreHole`, but it sounds suboptimal: it requires the atom indexes too... Moreover, they might be other sections that do not fall under `AtomsParameters`. I'd rather have a push-system that works for any `AtomsGroup` - Methods.subs_section pair. Any ideas?
2. The computation of `Method.charge` is contingent on `CoreHole`. Same remark as above.
3. `CoreHole` is in many cases specified in the same parsed blocks / files as `Pseudopotential`. I'm trying to package both together in each new implementation now.

2023-12-12 06:39 UTC, lauri-codes commented
I think the parser is ultimately responsible for setting all connections in place. A normalizer could very well be used to e.g. check the validity of the data or to add new derived data.

Note that it is of course fine to have a single unified **function** in e.g. `nomad` or in the `electronicparsers` package that is shared between all parsers and resolves all the references.

2023-12-12 07:12 UTC, ndaelman-hu commented
> I think the parser is ultimately responsible for setting all connections in place. A normalizer could very well be used to e.g. check the validity of the data or to add new derived data.
> 
> Note that it is of course fine to have a single unified **function** in e.g. `nomad` or in the `electronicparsers` package that is shared between all parsers and resolves all the references. I think this approach is often used in the `atomisticparsers` package, where several tasks are common for the parsers.

I get your point, in that the logical structure of the output may vary and this is where the parser has to jump in, of course.
However, the schema on our side will always be `AtomsGroup` pointing to `CoreHole`, where the latter may alter the overall `charge` (and is often set along with the `Pseudopotential`).

For anyone extending the parsers, this structure is far from obvious, nor is it clearly communicated anywhere.
My first instinct, for example, was to extend `AtomsGroup`, rather than `Method`. I think we have to communicate these kinds of designs better to other (external) devs, since we're headed in the direction of a modular platform.

Maybe a _normalizer_ is not appropriate here. Another option that come to mind is a `FactoryMethod`, which delivers (maybe even sets) a `AtomsGroup` - `CoreHole` pair. If we go this route, where would this best be added? In `util.py`?

2023-12-12 07:48 UTC, lauri-codes commented
My first suggestion would be to include the method in the `electronicparsers` repo if it is only relevant for these parsers. But if the implementation should be shared across different parser repos, then `util.py` is an option.

2023-12-12 07:53 UTC, ndaelman-hu commented
@ondracka From the [OpenMX documentation](https://www.openmx-square.org/openmx_man3.9/node192.html), I'm understanding that CLBEs are computed using $\Delta$-SCF between the _initial_ (containing the corrected pseudopotential) and _final_ state (corrected pseudopotential + electron removed). Is this correct?

I'm asking, since the terminology is confusing with [VASP's](https://www.vasp.at/wiki/index.php/ICORELEVEL), where _initial-state approximation_ (`icorelevel = 1`) is a single SCF with Koopman. There, the $\Delta$-SCF is between a regular groundstate (same pseudopotential) and a _final-state approximation_ (`icorelevel = 2`).

2023-12-12 08:35 UTC, ondracka commented
> @ondracka From the [OpenMX documentation](https://www.openmx-square.org/openmx_man3.9/node192.html), I'm understanding that CLBEs are computed using Δ-SCF between the _initial_ (containing the corrected pseudopotential) and _final_ state (corrected pseudopotential + electron removed). Is this correct?

That is my understanding as well.

2023-12-12 08:38 UTC, ndaelman-hu commented
> > @ondracka From the [OpenMX documentation](https://www.openmx-square.org/openmx_man3.9/node192.html), I'm understanding that CLBEs are computed using Δ-SCF between the _initial_ (containing the corrected pseudopotential) and _final_ state (corrected pseudopotential + electron removed). Is this correct?
> 
> That is my understanding as well.

Okay, great! I'm close to finishing with OpenMX too, will request you to review then.

2023-12-18 21:14 UTC, JosePizarro3 commented
Btw, is something included in the TBStudio parser regarding the active atom?

2023-12-19 09:45 UTC, ndaelman-hu commented
> Btw, is something included in the TBStudio parser regarding the active atom?

Hey, thx for mentioning TBStudio. I had to rebase first, now I can see that parser too.
Atm, it does not assign any `atoms_group`s, so it won't break with any of my changes.
I will add support when extending `core_hole` to atomic orbitals in general. I'll open an issue this evening.

2023-12-19 10:12 UTC, ladinesa reviewed
Some miinor suggestions.

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +    @property
why is this a  property?

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +            logger.error(f'Species definition must be of length 3: {definitions}')
should you return here?

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +                logger.error(f'Unknown l-quantum symbol: {quantum_nums[1]}')
should you return here?

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
no self.logger?

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +        sec_system = self.archive.run[-1].system[-1]
error handling here

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/vasp/parser.py
> +                species_electrons -= param.core_hole.n_electrons_excited
what is the initial value for species_electrons

2023-12-19 10:12 UTC, ladinesa commented on electronicparsers/vasp/parser.py
> +                self.archive.run[-1].method[-1].atom_parameters[corehole_id].core_hole = core_hole
no need for error handling here?

2023-12-19 10:17 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +    @property
Simply easier access: essentially this is a dynamically generated dictionary
It's accessed 2x later on

2023-12-19 10:19 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
Is it not passed as an argument of `parse`?

2023-12-19 10:23 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +    @property
why not simply have a get function. a property should depend on a state somehow.

2023-12-19 10:24 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
what i meant was you do not need to pass as arg to parse_method if it is class attr.

2023-12-19 10:42 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +                species_electrons -= param.core_hole.n_electrons_excited
Isn't it `param.n_electrons`? Else the loop breaks.

2023-12-19 10:48 UTC, ladinesa commented on electronicparsers/vasp/parser.py
> +                species_electrons -= param.core_hole.n_electrons_excited
i see

2023-12-19 10:52 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +        self.parse_configurations(
I held off on resolving this discussions due to changes at the time.
No arguments are being passed to `parse_configurations`, so it is essentially taken care off.

Just a small point of feedback. While your suggestion definitely improves readability, it comes with the downside of coupling the input of `parse_configurations` to the output from `parse_method`. That coupling is too strong, and therefore a fatal design flaw.
In this case, it would be better to keep this format (closer to functional programming), OR have `parse_configurations` collect the various output packages of other methods `parse_...`.
In that case it's still coupled, but less. The final decision depends on how likely those methods are to be removed.

2023-12-19 11:01 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +    @property
I'm sorry, I'm not seeing the distinction: is the `atom_index_dict` a state of `self.archive`?
I can also change this to a `cached_property` decorator, but that might be overkill for 2-time use

2023-12-19 11:03 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +    @property
Sorry, it's actually accessed in a loop, so caching might be advantageous

2023-12-19 11:03 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +                species_electrons -= param.core_hole.n_electrons_excited
can I resolve?

2023-12-19 11:05 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +    @property
but everytime you access this, it evaluates it. you can have self._atom_index_dict that can be reset if some dependency changes.

2023-12-19 11:08 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
Is it a class attribute? I'm only seeing it passed as an argument to `OpenmxParser.parse()`.
Moreover, wouldn't the alternative be more of an object attribute instead?

2023-12-19 11:12 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
Yes that was I was asking if it is a class attr, if not maybe add it under parse.

2023-12-19 11:15 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +                    sec_system.atoms_group = []
@ladinesa I guess this is redundant then, thanks to the instantiation process

2023-12-19 11:16 UTC, ladinesa commented on electronicparsers/vasp/parser.py
> +                    sec_system.atoms_group = []
yes it is.

2023-12-19 11:18 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +    @property
> but everytime you access this, it evaluates it

as is, yes, but not if I cache it

2023-12-19 11:21 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
I was following the example of `parse_species`, but this is a free-standing method.
We might want to stratify the interface.

2023-12-19 11:26 UTC, ladinesa commented on electronicparsers/openmx/parser.py
> +        self.parse_method(logger)
yes this is already implemented in the abstract class for parsers that I am developing in https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1538

2023-12-19 11:51 UTC, ndaelman-hu commented
> Very nice. Please, don't forget to change also `workflowparsers/quantum_espresso_xspectra` with the new `CoreHoleSpectra`.
> 
> I will keep up with the discussion about nesting AtomsGroup.
> 
> **Btw, can you share some examples and add testing?**

@JosePizarro3 Can you pls lift the change request in your review. That applied to an old version.
Your suggestions have been incorporated.

2023-12-19 12:09 UTC, JosePizarro3 approved these changes

2023-12-20 14:13 UTC, merged