Use run schema plugin
nomad-coe/electronic-parsers pull request #191
Opened 2023-12-06 23:26 UTC by ladinesa

See https://github.com/nomad-coe/nomad-schema-plugin-run.git

2023-12-07 06:55 UTC, ndaelman-hu commented
Will review this afternoon, after my FAIRmat Café.

2023-12-07 13:50 UTC, ndaelman-hu commented
I was merging the `CoreHole`... I'm going to have to do a massive rebase, won't I?

2023-12-07 14:05 UTC, ndaelman-hu requested changes
There are several unused imports in the metainfo. I guess they can be removed?

```
./electronicparsers/exciting/metainfo/exciting.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/charmm/metainfo/charmm.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/elk/metainfo/elk.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/fplo/metainfo/fplo_temporaries.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/fplo/metainfo/fplo_input_autogenerated.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/fplo/metainfo/fplo.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/ams/metainfo/ams.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/molcas/metainfo/molcas.py: from nomad.datamodel.metainfo import simulation
./electronicparsers/w2dynamics/metainfo/w2dynamics.py: CPU time used for the QMC simulation
./electronicparsers/cp2k/metainfo/cp2k.py: for a linear scaling simulation Specify the type of simulation
./build/lib/electronicparsers/nwchem/metainfo/nwchem.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/exciting/metainfo/exciting.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/turbomole/metainfo/turbomole.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/crystal/metainfo/crystal.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/fleur/metainfo/fleur.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/fhiaims/metainfo/fhi_aims.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/cpmd/metainfo/cpmd_general.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/cpmd/metainfo/cpmd.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/gamess/metainfo/gamess.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/charmm/metainfo/charmm.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/elk/metainfo/elk.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/dmol3/metainfo/dmol3.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/onetep/metainfo/onetep.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/vasp/metainfo/vasp_incarsOut.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/vasp/metainfo/vasp_incarsUnknown.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/vasp/metainfo/vasp_incars.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/vasp/metainfo/vasp.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/castep/metainfo/castep.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/gaussian/metainfo/gaussian.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/octopus/metainfo/octopus_autogenerated.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/octopus/metainfo/octopus.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/wien2k/metainfo/wien2k.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/gpaw/metainfo/gpaw.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/siesta/metainfo/siesta.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/siesta/metainfo/siesta_autogenerated.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/qbox/metainfo/qbox.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/yambo/metainfo/yambo.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/abacus/metainfo/abacus.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/mopac/metainfo/mopac.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/fplo/metainfo/fplo_temporaries.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/fplo/metainfo/fplo_input_autogenerated.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/fplo/metainfo/fplo.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/abinit/metainfo/abinit_autogenerated.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/abinit/metainfo/abinit.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/ams/metainfo/ams.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/molcas/metainfo/molcas.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/orca/metainfo/orca.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/quantumespresso/metainfo/quantum_espresso.py: from nomad.datamodel.metainfo import simulation
./build/lib/electronicparsers/cp2k/metainfo/cp2k.py: from nomad.datamodel.metainfo import simulation for a linear scaling simulation Specify the type of simulation
./build/lib/electronicparsers/psi4/metainfo/psi4.py: from nomad.datamodel.metainfo import simulation
```

2023-12-07 14:36 UTC, ndaelman-hu commented
Comparing the output from the updated files
`for i in $(find . -type f | grep -e '.py$'); do a=$(grep 'import runschema$' $i); if [[ $a ]]; then echo $i; fi; done | sort`
and the distribution of parser-specific metainfos
`for i in $(find electronicparsers/*/metainfo/. -type f | grep -e '.py$'); do if [[ ! $(echo $i | grep '__init__.py') ]]; then echo $i; fi; done | sort`
the following files have not been changed:

```
electronicparsers/atk/metainfo/./atk.py
electronicparsers/charmm/metainfo/./charmm.py
electronicparsers/fplo/metainfo/./fplo_temporaries.py
electronicparsers/fplo/metainfo/./fplo_input_autogenerated.py
electronicparsers/fplo/metainfo/./fplo.py
electronicparsers/molcas/metainfo/./molcas.py
electronicparsers/openmx/metainfo/./openmx.py
```

Just double-check them to be sure.

2023-12-11 19:53 UTC, ndaelman-hu commented
> There are several unused imports in the metainfo. I guess they can be removed?
> 
> searched via `for i in $(find . -type f | grep -e '.py$'); do a=$(grep 'simulation$' $i); if [[ $a ]]; then echo $i: $a; fi; done` and then manually pruned
> 
> ```
> ./electronicparsers/exciting/metainfo/exciting.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/charmm/metainfo/charmm.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/elk/metainfo/elk.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/fplo/metainfo/fplo_temporaries.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/fplo/metainfo/fplo_input_autogenerated.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/fplo/metainfo/fplo.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/ams/metainfo/ams.py: from nomad.datamodel.metainfo import simulation
> ./electronicparsers/molcas/metainfo/molcas.py: from nomad.datamodel.metainfo import simulation
> ```

Shouldn't `simulation.run.Run` be replaced too? It's present in many `metainfo` folders, and some `parser.py` files.

2023-12-12 08:50 UTC, ladinesa commented
> > There are several unused imports in the metainfo. I guess they can be removed?
> > searched via `for i in $(find . -type f | grep -e '.py$'); do a=$(grep 'simulation$' $i); if [[ $a ]]; then echo $i: $a; fi; done` and then manually pruned
> > ```
> > ./electronicparsers/exciting/metainfo/exciting.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/charmm/metainfo/charmm.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/elk/metainfo/elk.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/fplo/metainfo/fplo_temporaries.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/fplo/metainfo/fplo_input_autogenerated.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/fplo/metainfo/fplo.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/ams/metainfo/ams.py: from nomad.datamodel.metainfo import simulation
> > ./electronicparsers/molcas/metainfo/molcas.py: from nomad.datamodel.metainfo import simulation
> > ```
> 
> Shouldn't `simulation.run.Run` be replaced too? It's present in many `metainfo` folders, and some `parser.py` files.

I do not see any of these simulation.run.Run

2023-12-12 10:39 UTC, JosePizarro3 commented
Hi there,

@JFRudzinski this also interests you.

I am back from my vacation, and I saw this and it draw my attention. I thought that we were going to work out the transition to data and the new schema, in an independent branch in NOMAD, then, we would define a plugin with the new computational schema and migrate the parsers to plugin parsers.

I understand this merge is now creating an intermediate step. We now migrate run into a plugin, which then changes ALL the parsers. Then we define data and **once more** change ALL the parsers. We can of course do this, but I would avoid doing double-work on having to change all the parsers in a time frame of 2-3 months. Or what is the objective of this migration, @ladinesa? 

I understand that for `workflow2` this is useful, as it is anyways very up-to-date, but for `run` I think is overkill.

2023-12-12 10:45 UTC, ladinesa commented
> Hi there,
> 
> @JFRudzinski this also interests you.
> 
> I am back from my vacation, and I saw this and it draw my attention. I thought that we were going to work out the transition to data and the new schema, in an independent branch in NOMAD, then, we would define a plugin with the new computational schema and migrate the parsers to plugin parsers.
> 
> I understand this merge is now creating an intermediate step. We now migrate run into a plugin, which then changes ALL the parsers. Then we define data and **once more** change ALL the parsers. We can of course do this, but I would avoid doing double-work on having to change all the parsers in a time frame of 2-3 months. Or what is the objective of this migration, @ladinesa?
> 
> I understand that for `workflow2` this is useful, as it is anyways very up-to-date, but for `run` I think is overkill.

This addresses Area D's effort to transition into separating domain-specific parts of the nomad lab package from the core infrastructure. This can be done independently of the transition into data. The new schemas and parsers for when we do the transition into data will all be plug ins and you can put it them anywhere you like, not necessarily on the same plug that are defined in this pr.

2023-12-12 10:49 UTC, JosePizarro3 commented
> This addresses Area D's effort to transition into separating domain-specific parts of the nomad lab package from the core infrastructure. This can be done independently of the transition into data. The new schemas and parsers for when we do the transition into data will all be plug ins and you can put it them anywhere you like, not necessarily on the same plug that are defined in this pr.

Sure, I understand. Just mentioning that the imports are going to change anyways in 2-3 months, and that the nomad-schema-plugin-run git will be soon deprecated.

2023-12-12 10:53 UTC, ladinesa commented
> > This addresses Area D's effort to transition into separating domain-specific parts of the nomad lab package from the core infrastructure. This can be done independently of the transition into data. The new schemas and parsers for when we do the transition into data will all be plug ins and you can put it them anywhere you like, not necessarily on the same plug that are defined in this pr.
> 
> Sure, I understand. Just mentioning that the imports are going to change anyways in 2-3 months, and that the nomad-schema-plugin-run git will be soon deprecated.

Yes of course, but we also would like to work on this nomad core package now. Actually this would make the transition to data seamless since you will then not have to worry about any references to the old schema in the core nomad.

2023-12-12 13:06 UTC, ndaelman-hu commented
> > > There are several unused imports in the metainfo. I guess they can be removed?
> > > searched via `for i in $(find . -type f | grep -e '.py$'); do a=$(grep 'simulation$' $i); if [[ $a ]]; then echo $i: $a; fi; done` and then manually pruned
> > > ```
> > > ./electronicparsers/exciting/metainfo/exciting.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/charmm/metainfo/charmm.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/elk/metainfo/elk.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/fplo/metainfo/fplo_temporaries.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/fplo/metainfo/fplo_input_autogenerated.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/fplo/metainfo/fplo.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/ams/metainfo/ams.py: from nomad.datamodel.metainfo import simulation
> > > ./electronicparsers/molcas/metainfo/molcas.py: from nomad.datamodel.metainfo import simulation
> > > ```
> > 
> > 
> > Shouldn't `simulation.run.Run` be replaced too? It's present in many `metainfo` folders, and some `parser.py` files.
> 
> I do not see any of these simulation.run.Run

Ha, sorry, probably was on the wrong branch. Yeah, it seems taken care off.

2023-12-12 13:10 UTC, ndaelman-hu commented
> I was merging the `CoreHole`... I'm going to have to do a massive rebase, won't I?

@ladinesa For outstanding PRs in `electronicparsers`, do we now have to migrate to this new repo? How should we transition fluently?
If migrating is quite involved, could we possible first merge (I have only 1 PR) by a certain date, e.g. 20.12?

2023-12-12 13:18 UTC, ladinesa commented
> > I was merging the `CoreHole`... I'm going to have to do a massive rebase, won't I?
> 
> @ladinesa For outstanding PRs in `electronicparsers`, do we now have to migrate to this new repo? How should we transition fluently? If migrating is quite involved, could we possible first merge (I have only 1 PR) by a certain date, e.g. 20.12?

The plan is to have each code its own parser plug in. So once chema is done with the new schena for data, I will slowly move each electronicparser to their own plug in, I will see if there is a PR that concerns this particular parser, if there is, I will probably ask you to finalize it or I will skip it then come back once you are done.

2023-12-13 09:23 UTC, ndaelman-hu approved these changes
Okay, this was quite extensive, but also repetitive. If you did this manually, kudos to you for keeping up the consistency, though I have the feeling that an advanced linter like Ruff may have been used.
**This PR also updates object instantiation, pls mention that in the final description.**

I just dropped a couple of questions (for myself) & a bunch of comments (mostly `double assignment?`). Those aren't anything major, so you can neglect them if you wish too. Some of the takeaways:

- So, a few coupled instantiations pop up all the time, e.g. `DFT` and `Electronic`, `System` and `Atoms`. Maybe we could start considering Factory pattern for these common cases?
- Does Ruff have anything against multiple assignment, e.g. `sec_dft, sec_elec = DFT(). Electronic()`?
- Does Ruff have anything against conditional assignments, e.g. `sec_dft = DFT() if sec_dft is None else []`?
- Will `m_create` be deprecated then? Personally, I think its behavior was quite nice. Maybe we could see to handle section assignments in a more meta-programmatic way eventually?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abacus/metainfo/abacus.py
> +import runschema.run  # pylint: disable=unused-import
Regarding the pylinter, will this be changed under ruff?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/metainfo/abinit_autogenerated.py
General question: what are these `autogenerated` files?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/ams/parser.py
> +                sec_scc.multipoles.append(sec_multipoles)
Ow, interesting! Empty `list` instantiation is handled by the object?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/atk/parser.py
> +            sec_dft.xc_functional = sec_xc_functional
You could use double assignments to be more in-line with the other sections.
Not sure what ruff thinks about it, though.

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/atk/parser.py
> +            sec_system.atoms = sec_atoms
Same as previous comment

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/cp2k/metainfo/cp2k_general.py
same question about these `general` parsers

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/cp2k/parser.py
> +            sec_run.x_cp2k_section_end_information.append(sec_endinformation)
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/cp2k/parser.py
> +                    sub_section_def = section.m_def.all_sub_sections_by_section.get(sec_def.section_cls.m_def)[0]
2 points:
1. Can't you substitute `sec_def.section_cls.m_def` for `sub_section.m_def`?
2. To my knowledge, it isn't very Pythonic to define a variable like `sub_section_def` for a single use.

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/cp2k/parser.py
> +            sec_scf.energy = sec_scf_energy
At this point, `sec_scf_energy` and `sec_scf.energy` are equally long. I'm not seeing the point of introducing a variable, then.
Just keep in mind that it has 3 references in total.

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/edmft/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/fleur/parser.py
> +            sec_scf.eigenvalues.append(sec_eigenvalues)
triple assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/gaussian/parser.py
> +            sec_def = sec_scc.m_def.all_sub_sections_by_section.get(sec_class.m_def)[0]
non-Pythonic?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/gaussian/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/gpaw/parser.py
> +        sec_dft.xc_functional = sec_xc_functional
double assignment

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/gpaw/parser.py
> +        sec_system.atoms = sec_atoms
Double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/nwchem/parser.py
> +                sec_scf.energy = sec_scf_energy
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/nwchem/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/ocean/parser.py
> +        sec_system = System(atoms=sec_atoms)
Variable only used once

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/ocean/parser.py
> +            sec_system = System()
Only a single use...

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/octopus/parser.py
> +                sec_scf.energy = sec_scf_energy
I would replace `sec_scf_energy` for `sec_scf.energy`

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> +            return sec_scc
You could also place the `return` under the `if-else`

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> +        sec_method.gw = sec_gw
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/fhiaims/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/fhiaims/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +            sec_dataset.x_abinit_section_input = sec_input
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +        sec_method.electronic = sec_electronic
triple assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +                    sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +                sec_scf_iteration.energy = sec_energy
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/openmx/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/orca/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/orca/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/psi4/parser.py
> +            dft.xc_functional = xc_functional
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/quantumespresso/parser.py
> +        sec_method.electronic = sec_electronic
triple assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/soliddmft/parser.py
> +            sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/tbstudio/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/tbstudio/parser.py
> +        sec_tb.slater_koster = sec_sk
triple assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +        sec_system.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +            sec_system_cluster.atoms = sec_atoms
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +            sec_scc_module.energy = sec_scc_module_energy
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +                    sec_scc_thermo.energy = sec_scc_thermo_energy
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +            sec_iteration.energy = sec_iteration_energy
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/wannier90/parser.py
> +        sec_proj.wannier = sec_wann
double assignment?

2023-12-13 09:23 UTC, ndaelman-hu commented on electronicparsers/wien2k/parser.py
> +        sec_method.electronic = sec_electronic
double assignment?

2023-12-13 09:28 UTC, ndaelman-hu commented
> > > I was merging the `CoreHole`... I'm going to have to do a massive rebase, won't I?
> > 
> > 
> > @ladinesa For outstanding PRs in `electronicparsers`, do we now have to migrate to this new repo? How should we transition fluently? If migrating is quite involved, could we possible first merge (I have only 1 PR) by a certain date, e.g. 20.12?
> 
> The plan is to have each code its own parser plug in. So once chema is done with the new schena for data, I will slowly move each electronicparser to their own plug in, I will see if there is a PR that concerns this particular parser, if there is, I will probably ask you to finalize it or I will skip it then come back once you are done.

Okay, so in the short-term, we can keep working as is, great! Pls note that as the schema changes, you may also have to update the new `run` repo. Let us know if we can help out there.

I'm fully on-board with the individual parser plug-ins. Thank you for taking care of this migration!

2023-12-13 10:10 UTC, ladinesa commented on electronicparsers/abacus/metainfo/abacus.py
> +import runschema.run  # pylint: disable=unused-import
Probably, will take note of this.

2023-12-13 10:13 UTC, ladinesa commented on electronicparsers/abinit/metainfo/abinit_autogenerated.py
There are schemas generated by a script, I will try to find it. We can throw them away during the refactor.

2023-12-13 10:13 UTC, ladinesa commented on electronicparsers/ams/parser.py
> +                sec_scc.multipoles.append(sec_multipoles)
Repeating sub sections are empty lists by default.

2023-12-13 10:14 UTC, ladinesa commented on electronicparsers/atk/parser.py
> +            sec_dft.xc_functional = sec_xc_functional
sure, I can try.

2023-12-13 10:15 UTC, ladinesa commented on electronicparsers/turbomole/parser.py
> +                    sec_scc_thermo.energy = sec_scc_thermo_energy
no double assignement one is sec_scc_thermo_energy and one is sec_scc_thermo.energy

2023-12-13 10:15 UTC, ladinesa commented on electronicparsers/turbomole/parser.py
> +            sec_iteration.energy = sec_iteration_energy
same

2023-12-13 10:16 UTC, ladinesa commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
which one?

2023-12-13 10:16 UTC, ladinesa commented on electronicparsers/wannier90/parser.py
> +        sec_proj.wannier = sec_wann
which one?

2023-12-13 10:17 UTC, ladinesa commented
> changes

I suggest we continue all schema devs in the new simulation data schema.

2023-12-13 12:02 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
`DFT` and `Electronic`. Didn't highlight that well

2023-12-13 12:05 UTC, ladinesa commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
ah you mean sec_dft, sec_electronic = DFT(), Electronic()

2023-12-13 12:08 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
Even ```
sec_dft, sec_electronic = DFT(), Electronic()
sec_method.dft, sec_method.electronic = sec_dft, sec_electronic
```

2023-12-13 12:12 UTC, ladinesa commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
not a big fan actually, hehe but I will look at the fashionable way. thanks

2023-12-13 12:12 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +                    sec_scc_thermo.energy = sec_scc_thermo_energy
Yeah, I might've been a bit overzealous here. Again, these are not huge deals, it's up to you (and Ruff) whether you change it or keep it.

You can still apply 
```
sec_thermo, sec_scc_thermo_energy = Thermodynamics(), Energy()
```
and in many of the comments reduce the 4 lines even to 2.

That's what I mean with all these double / triple assignments.

2023-12-13 12:35 UTC, ndaelman-hu commented on electronicparsers/turbomole/parser.py
> +        sec_method.electronic = sec_electronic
@ladinesa 
Btw, just want to use this here as an example to point out something that bothers me in general with these parsers:

`sec_method.dft, sec_method.electronic` are both singly occurring (and non-repeating) sections, right?
It would be awesome to have such cases (which are a majority) act as _singletons_ that automatically get stored in the right `archive` section. If said section does not exist, then throw an error.

As such, I don't have to worry about setting trivial sections. Filling quantities can then work as above or just via `DFT().xc_functional_name = ...` whenever necessary.

Repeating sections could add a new object via instantiation, while accessing them using `list` syntax. (e.g. `Run[-1]`)
Sections with multiple occurrences could have the parent section passed as an argument, i.e. `Eigenvalues(Bandstructure)`.
All cases can be covered by this syntax.

I realize that this delves deep into meta-programming, which might be confusing to more advanced users.
Still, Python is very enabling here, and **I'd love to discuss the option sometime**.

2024-02-02 10:19 UTC, JosePizarro3 commented
This branch has not been merged, but Gitlab is pointed to it.

2024-02-05 12:14 UTC, ladinesa commented
I will simply merge this.

2024-02-05 12:14 UTC, merged