Fix CP2K restart file
nomad-coe/electronic-parsers pull request #195
Opened 2024-02-05 11:27 UTC by JosePizarro3

See [#1879](https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/1879)

2024-02-05 14:34 UTC, aalbino2 requested changes
I think project_name variable should be fetched from the very first lines of the output file, and we should try to see whether such a restart file is found.

In summary the possible filenames one can find are:
* input_filename
* {project_name}-1.restart

There is not the case in which a file such {input_filename}-1.restart is generated by cp2k

2024-02-05 14:34 UTC, aalbino2 commented on electronicparsers/cp2k/parser.py
> +                'file if CP2K has appended -1 to the .restart file name.'
the -1 part is not clear, I think. 

We would need not to use the input_filename + "-1" but the project_filename fetched from the output file. 

What about a warning like this?

f" Input .inp not found. We will attempt finding the restart file with following sintax 'project_name'-1.restart: {project_name}-1.restart"

2024-02-05 14:34 UTC, aalbino2 commented on electronicparsers/cp2k/parser.py
> +                appended_filename = input_filename.split('.restart')[0] + '-1.restart'
here, you should parse the project_name instead using again the input_filename

2024-02-06 10:42 UTC, JosePizarro3 commented
Ok, I am extracting now `project_name = self.settings.get('global', {}).get('project_name')` and using it to append `f'{project_name}-1.restart'`.

Feel free to resolve the previous comments.

2024-02-06 10:43 UTC, aalbino2 approved these changes
All good!

2024-02-06 11:21 UTC, merged