Update `FrequencyMesh`
nomad-coe/electronic-parsers pull request #79
Opened 2023-04-05 07:00 UTC by ndaelman-hu

2023-04-05 10:03 UTC, JosePizarro3 commented
Could you please add a very simple assertion for Wannier90 regarding the k_mesh.points?

2023-04-14 18:34 UTC, JosePizarro3 reviewed
Done with the review. Mainly being consistent when coding and restoring the changes dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/abinit/parser.py
> +            freq_points = freqs[:, 0] + freqs[:, 1] * 1j
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/abinit/parser.py
> +            sec_freq_mesh = FrequencyMesh(n_points=len(freqs), points=freq_points)  # TODO: check
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> +                str_operation=str_to_array, unit=1 / ureg.bohr, repeats=False, convert=False)
delete jump to next line so ] falls in this one.

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
this is creating 2 KMesh sections, once here and once below. I'd say we can keep `x_exciting_xs_ngridk` and delete the next lines after this where you are creating KMesh and asigning the grid.

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> +        freq_points = [freqmin + i * (freqmax - freqmin) / n_freqs for i in range(n_freqs)] * ureg.hartree
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> +            # type=sec_gw.x_exciting_freqgrid.x_exciting_fgrid,  # TODO: map into enum
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> +            points=freq_points,  # TODO: check
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/fhiaims/parser.py
> +        sec_k_mesh.grid = self.out_parser.get('k_grid', [1, 1, 1])  # AIMS does not have a guaranteed PBC, this default should be omitted
change to None by default, i.e., delete `[1, 1, 1]` lines

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/fhiaims/parser.py
> +            freq_points = np.array(frequency_data)[:, 1] * ureg.hartree
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/fhiaims/parser.py
> +            freq_points = None
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/fhiaims/parser.py
> +            # type=self.out_parser.get('freq_grid_type'),  # TODO: set default value for enum
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/fhiaims/parser.py
> +            points=freq_points)
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +
too many blank lines

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_abinitparser.py
> +    assert sec_gw.frequency_mesh.points[-1].to('eV').magnitude == approx(31.855950000000004j)  # TODO: check
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +            sec_k_mesh.points = [[0.] * 3]
not a big fan of this typing; can you please use `[0.0, 0.0, 0.0]`?

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.grid) == [6] * 3
`assert (sec_method.k_mesh.grid == np.array([6, 6, 6])).all()`

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.offset) == [.0] * 3
`assert (sec_method.k_mesh.offset== np.array([0.0, 0.0, 0.0])).all()`

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.grid) == [6] * 3
`assert (sec_method.k_mesh.grid == np.array([6, 6, 6])).all()`

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.offset) == [.0] * 3
`assert (sec_method.k_mesh.offset == np.array([0.0, 0.0, 0.0])).all()`

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.grid) == [8] * 3
and here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.offset) == [.0] * 3
and here?

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.grid) == [12] * 3
and here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.offset) == [0.097, 0.273, 0.493]
and here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    # assert sec_gw.frequency_mesh.type == 'gauleg2'
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert sec_gw.frequency_mesh.points[4].to('hartree').magnitude == approx(0.125 + 0j)  # TODO: check
restore this, dealt with in https://github.com/nomad-coe/electronic-parsers/pull/80

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.grid) == [6, 6, 4]
here too, (...).all()

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_excitingparser.py
> +    assert list(sec_method.k_mesh.offset) == [0.] * 3
here too, (...).all()

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [16] * 3
and here, more verbose and use (...).all()

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_methods[0].k_mesh.grid) == [8] * 3
and here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [16] * 3
I think you got my point by now 😄

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [10] * 3
here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [2] * 3
here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [12] * 3
more verbose please

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [1] * 3
here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert sec_method[-1].gw.frequency_mesh.n_points == len(sec_method[-1].gw.frequency_mesh.points)
restore this, dealt with in #80

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [8] * 3
and here

2023-04-14 18:34 UTC, JosePizarro3 commented on tests/test_quantumespressoparser.py
> +    assert len(sec_method.k_mesh.points) == 1
Does k_mesh make any sense for MD?

2023-04-14 18:46 UTC, ndaelman-hu commented on electronicparsers/abinit/parser.py
> +            freq_points = freqs[:, 0] + freqs[:, 1] * 1j
If it is implemented in #80, then it will get solved when merging.
Are you ready with that PR?

2023-04-14 18:49 UTC, ndaelman-hu commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [12] * 3
what do you mean with _more verbose_?

2023-04-14 18:52 UTC, ndaelman-hu commented on electronicparsers/vasp/parser.py
> +            sec_k_mesh.points = [[0.] * 3]
Any better reason than aesthetics?

2023-04-14 18:59 UTC, ndaelman-hu commented on tests/test_fhiaimsparser.py
> +    assert list(sec_method.k_mesh.grid) == [16] * 3
Yeah, no need to repeat it at each statement, but thank you for the effort.

2023-04-14 20:22 UTC, ndaelman-hu commented on tests/test_quantumespressoparser.py
> +    assert len(sec_method.k_mesh.points) == 1
It's run in an ab initio code with pbc and it has a k mesh. You're right, in that in somewhat detracts from the main point.
Tbh, I'm fine either way, but I'm not going to push just for ambivalent stuff.

What I mostly want from a review is feedback on design, logical, implementation or performance errors, including for use cases that I didn't predict. Style matters in as much as it violates PEP8 or the native pycodestyle.

2023-04-14 21:04 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
> this is creating 2 KMesh sections, once here and once below

**Could you pls clarify?** If you mean in the output, it shouldn't, since the section is not repeated. Indeed, I couldn't find any double sections in the tests, `x_exciting_xs_ngridk` included. **Do you have a parsed example output to help see where it is doubled?**
Moreover, I thought that GW or BSE create a new entry?

> I'd say we can keep `x_exciting_xs_ngridk` and delete the next lines after this where you are creating KMesh and asigning the grid.

The point of this PR is to apply the `KMesh` mapping, which is lacking in most parsers (extraction, as here, is mostly present). So I would rather cut out `x_exciting_xs_ngridk`. I didn't touch it in the excited state section, since you preferred to update it yourself. That's fine.

2023-04-14 22:41 UTC, JosePizarro3 requested changes
Ok, I have several comments here that I want you to deal with, because this is being too time consuming.

This is a TODO:
- [x] Please, revert the changes you did for FrequencyMesh. There is more than what you did, and it is going to be impossible to track the differences.
- [ ] Also change back the exciting `xs/ngridk` KMesh parsing, as right now I am guessing it is incorrect and producing errors that you are not able to debug. I can deal with the repeated quantities in a separate issue, as it is a good practice.

And please:
- Can you let the comments unresolved? I am working on checking the github directly. Everytime you resolve, I have to open and close each one to see what is going on... This is very cumbersome.
- Style also goes beyond PEP8 and pycodestyle. I understand some students and developers see this as a secondary thing, but keeping a structure in the code makes it more readable for later people. Now someone will arrive after you, will look into VASP or QE and will think: wtf, how are they so different? Not to speak of the other 30 ab initio parsers...
- In any case, I admit these things are kind of subjective. My comments are mostly line by line, similar to reviewing a thesis or a paper (that's why might look kind of repetitive), and are mostly suggestions, so no need to accept them 🙂

2023-04-14 22:41 UTC, JosePizarro3 commented on electronicparsers/abinit/parser.py
> +            freq_points = freqs[:, 0] + freqs[:, 1] * 1j
No, you are including further changes here distinct from #80. Please @ndaelman-hu undo these changes. Otherwise it is going to be impossible to track down and we are going to overlook them.....

2023-04-14 22:41 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
With this I meant that you are creating in this method a KMesh, and then in line 1795-1796 creating another KMesh and populating it using `x_exciting_xs_ngridk`, for which probably you are overwritting KMesh...

There are files in the main installation from BSE for exciting that you can try.

But @ndaelman-hu once more, please read what you are changing: here you are modifying parsing from the xs input file... This `ngridk` only applies in the group named `xs`...

2023-04-14 22:41 UTC, JosePizarro3 commented on electronicparsers/abinit/parser.py
> +            freq_points = freqs[:, 0] + freqs[:, 1] * 1j
Please, don't resolve these conversations until they are really resolved by me.

2023-04-14 22:41 UTC, JosePizarro3 commented on electronicparsers/vasp/parser.py
> +            sec_k_mesh.points = [[0.] * 3]
Not really, just to keep some sort of consistency in the parsers, but tbh is the same for me.

2023-04-18 10:04 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
Set back. To avoid future misinterpretations, I suggest that you add a description to `_parse_input_xs()` stating that it covers BSE specifically.

2023-04-18 10:20 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
This is implicit on the `xs`, and not only for BSE but also for TDDFT.

2023-04-18 11:17 UTC, ndaelman-hu commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
Well, that there's this addition just proves my point...
**Implicit is fine, explicit is better.** Documentation is a great tool for long-term maintenance.

2023-04-18 12:20 UTC, JosePizarro3 commented on electronicparsers/exciting/parser.py
> -        sec_method.x_exciting_xs_ngridk = self.input_xml_parser.get('xs/ngridk', [1, 1, 1])
yeah, you are right; I will start including docs for each method as far as I modify the parsers

2023-04-18 12:24 UTC, JosePizarro3 approved these changes
Everything looks nice 👍 Thanks! 

Merge it whenever you want.

2023-04-18 13:16 UTC, merged